name: run_tests

on: [push, pull_request]

jobs:
  test:
    strategy:
        fail-fast: false
        matrix:
            python-version: [3.6, 3.7, 3.8, 3.9]
            os: [macOs-latest, ubuntu-latest, windows-latest]

    runs-on:  ${{ matrix.os }}
    name: run tests
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
            python-version:  ${{ matrix.python-version }}
      - name: install
        run: |
          pip install -r requirements.txt
          pip install -r tests/requirements.txt
      - name: test
        run: |
          pip freeze
          nosetests --verbosity=3 --with-coverage --cover-package pyexcel_xlsxw --cover-package tests tests --with-doctest --doctest-extension=.rst README.rst docs/source pyexcel_xlsxw
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          name:  ${{ matrix.os }} Python ${{ matrix.python-version }}